# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    node_manager:
      repo: "WhatsARanjit/node_manager"
      ref: "0.7.3"
    ruby_task_helper:
      repo: "puppetlabs/ruby_task_helper"
      ref: "0.5.1"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "1.0.0"
  repositories:
    "stdlib":
      "repo": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "translate":
      "repo": "https://github.com/puppetlabs/puppetlabs-translate.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:
      repo: "https://github.com/puppetlabs/provision.git"
      ref: "1ddac67b8a6f829c545103185c05291a47e0776e"
    servicenow_tasks: 'https://github.com/puppetlabs/servicenow_tasks.git'
