---
instance: dev1234.service-now.com
user: admin
password: password
oauth_token: oauth_token
table: cmdb_ci
certname_field: fqdn
classes_field: u_puppet_classes
environment_field: u_puppet_environment
proxy_addr: 127.0.0.1
proxy_port: 1234